---
- name: python
  hosts: all
  gather_facts: no
  become: "yes"
  tags: server_install
  tasks:
    - name: "Ensure python"
      raw: "sudo apt update && sudo apt -y install python"

- name: common
  hosts: "all"
  become: "yes"
  roles:
    - { role: "common", tags: "common" }

- name: entrypoint
  hosts: "entrypoint"
  become: "yes"
  roles:
    - { role: geerlingguy.docker, tags: server_install }
    - { role: geerlingguy.certbot, tags: server_install }
    - { role: geerlingguy.pip, tags: server_install }
    - { role: avans-entrypoint, tags: server_deploy }
