---
# Zorg dat alle hosts python hebben geïnstalleerd
- hosts: all
  gather_facts: no
  tags: install
  tasks:
    - name: Ensure python
      raw: sudo apt update && sudo apt -y install python

# Zorg dat alle hosts/droplets deze instellingen krijgen doorgevoerd
- hosts: all
  tags: install
  roles:
    - role: common

# Zorg dat de entrypoint server(s) draaien
- hosts: entrypoint
  roles:
    - role: geerlingguy.docker
      tags: install
    - role: geerlingguy.certbot
      tags: install
    - role: geerlingguy.pip
      tags: install
    - role: avans-entrypoint
      tags: deploy

# Zorg dat de curriculumviewer server(s) draaien
#- name: Curriculum Viewer

# Zorg dat de sonarqube server(s) draaien
#- name: sonarqube
