---
# Ensure python is installed on remote host
- hosts: all
  gather_facts: no
  tags: install
  tasks:
    - name: Ensure python
      raw: sudo apt update && sudo apt -y install python

# Ensure common settings are set on all servers
- hosts: all
  tags: install
  roles:
    - role: common

# Ensure Entrypoint servers
- hosts: entrypoint
  roles:
    - role: geerlingguy.docker
      tags: install
    - role: geerlingguy.certbot
      tags: install
    - role: geerlingguy.pip
      tags: install
    - role: avans-entrypoint
      tags: deploy

# Ensure Curriculum Viewer servers
#- name: Curriculum Viewer

# Ensure SonarQube servers
#- name: sonarqube