---
- hosts: "all"
  become: "yes"
  roles:
    - { role: "common", tags: "common" }

- hosts: "Entrypoint"
  become: "yes"
  roles:
    - role: geerlingguy.docker
      tags: server_install
    - role: geerlingguy.pip
      tags: server_install
    - role: avans-entrypoint
      tags: server_deploy
