---
# Ensure python is installed on remote host
- name: python
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure python
      raw: sudo apt update && sudo apt -y install python

# Ensure common settings are set on all servers
- name: common
  hosts: all
  roles:
    - common

# Ensure Entrypoint servers
- name: entrypoint
  hosts: entrypoint
  roles:
    - geerlingguy.docker
    - geerlingguy.certbot
    - geerlingguy.pip
    - avans-entrypoint

# Ensure Curriculum Viewer servers
#- name: Curriculum Viewer

# Ensure SonarQube servers
#- name: sonarqube