---
- name: "Ensure {{ nginx_config_directory }}"
  file:
    state: directory
    path: "{{ nginx_config_directory }}"
    owner: "{{ nginx_config_owner }}"
    group: "{{ nginx_config_group }}"
    mode: 0755

- name: "Ensure {{ nginx_webroot_directory }}"
  file:
    state: directory
    path: "{{ nginx_webroot_directory }}"
    owner: "{{ nginx_config_owner }}"
    group: "{{ nginx_config_group }}"
    mode: 0755

- name: "Ensure nginx files in {{ nginx_config_directory }}"
  copy:
    src: "{{ local_nginx_config_directory }}"
    dest: "{{ nginx_config_directory }}../"
    owner: "{{ nginx_config_owner }}"
    group: "{{ nginx_config_group }}"
    mode: 0755
