---
- name: "Ensure nginx config directories"
  file:
    state: directory
    path: "{{ nginx_config_directory | regex_replace('^\\/', '') + '/' + item.path }}"
    dest: "{{ nginx_config_directory + '/' + item.path | replace('.j2', '') }}"
    owner: "{{ default_user.name }}"
    group: "{{ default_group.name }}"
    mode: 0755
  with_filetree: "../templates{{ nginx_config_directory }}"
  when: item.state == 'directory'

- name: "Ensure nginx files in {{ nginx_config_directory }}"
  template:
    src: "{{ nginx_config_directory | regex_replace('^\\/', '') + '/' + item.path }}"
    dest: "{{ nginx_config_directory + '/' + item.path | replace('.j2', '') }}"
    owner: "{{ default_user.name }}"
    group: "{{ default_group.name }}"
    mode: 0755
  with_filetree: "../templates/{{ nginx_config_directory }}"
  when: item.state == 'file'