---
  - name: "Ensure {{ nginx_config_directory }} exists"
    file:
      state: directory
      owner: "{{ nginx_config_owner }}"
      group: "{{ nginx_config_group }}"
      mode: 0755

  - name: "Ensure {{ nginx_webroot_directory }} exists"
    file:
      state: directory
      owner: "{{ nginx_config_owner }}"
      group: "{{ nginx_config_group }}"
      mode: 0755

  - name: "Ensure nginx files are present in {{ nginx_config_directory }}"
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ nginx_config_owner }}"
      group: "{{ nginx_config_group }}"
      mode: 0755
    with_items: "{{ nginx_config_requirements }}"
